@props(['agency', 'documentTitle' => 'Document', 'controlNo' => null, 'verificationUrl' => null])
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $documentTitle ?? 'Document' }}</title>
    <style>
        @page { margin: 90px 40px 70px 40px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #1e293b; }
        table { border-collapse: collapse; width: 100%; }
        th, td { padding: 4px 6px; text-align: left; }
        .header { position: fixed; top: -75px; left: 0; right: 0; height: 75px; border-bottom: 2px solid #1d4ed8; padding-bottom: 6px; }
        .footer { position: fixed; bottom: -55px; left: 0; right: 0; height: 50px; border-top: 1px solid #cbd5e1; padding-top: 6px; font-size: 8px; color: #64748b; }
        .agency-name { font-size: 13px; font-weight: bold; color: #1d4ed8; }
        .doc-title { font-size: 15px; font-weight: bold; text-transform: uppercase; margin-top: 4px; }
        .control-no { font-size: 10px; color: #64748b; }
        .section-title { font-size: 11px; font-weight: bold; text-transform: uppercase; color: #1d4ed8; border-bottom: 1px solid #cbd5e1; margin: 14px 0 6px; padding-bottom: 3px; }
        .items-table th { background: #eff6ff; font-size: 9px; text-transform: uppercase; color: #1d4ed8; border-bottom: 1px solid #bfdbfe; }
        .items-table td { border-bottom: 1px solid #e2e8f0; font-size: 10px; }
        .text-right { text-align: right; }
        .signatories { width: 100%; margin-top: 30px; }
        .signatories td { text-align: center; vertical-align: top; padding-top: 30px; }
        .sig-line { border-top: 1px solid #1e293b; padding-top: 3px; font-size: 9px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 9px; font-weight: bold; background: #f1f5f9; }
        .muted { color: #64748b; }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td style="width: 70%;">
                    <div class="agency-name">{{ $agency->name }}</div>
                    <div class="muted">{{ $agency->address }}</div>
                    <div class="doc-title">{{ $documentTitle }}</div>
                </td>
                <td style="width: 30%; text-align: right;" class="control-no">
                    Control No.<br><strong>{{ $controlNo ?? '—' }}</strong>
                </td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <table>
            <tr>
                <td style="width: 70%;">Generated by {{ config('app.name') }} on {{ now()->format('F d, Y g:ia') }}. This is a system-generated document.</td>
                <td style="width: 30%; text-align: right;">Page <span class="pagenum"></span></td>
            </tr>
        </table>
    </div>

    {{ $slot }}

    @if($verificationUrl)
        <table class="signatories" style="margin-top: 20px;">
            <tr>
                <td style="width: 20%; text-align: left; padding-top: 0;">
                    <x-qr-code :value="$verificationUrl" :size="70" />
                </td>
                <td style="width: 80%; text-align: left; padding-top: 10px;" class="muted">
                    Scan to verify this document's authenticity, or visit:<br>{{ $verificationUrl }}
                </td>
            </tr>
        </table>
    @endif
</body>
</html>
