<x-pdf-layout :agency="$agency" :document-title="$documentTitle" :control-no="$controlNo" :verification-url="$verificationUrl">
    <table>
        <tr>
            <td style="width: 50%;"><strong>Purchase Request No.:</strong> {{ $caf->purchaseRequest->pr_no }}</td>
            <td style="width: 50%;"><strong>Status:</strong> {{ $caf->status->label() }}</td>
        </tr>
        <tr>
            <td><strong>Division:</strong> {{ $caf->purchaseRequest->division?->name }}</td>
            <td><strong>Fiscal Year:</strong> {{ $caf->purchaseRequest->fiscalYear?->year }}</td>
        </tr>
        <tr>
            <td><strong>Fund Source:</strong> {{ $caf->fundSource?->name }}</td>
            <td><strong>UACS Code:</strong> {{ $caf->uacsCode?->code }}</td>
        </tr>
    </table>

    <p class="section-title">Certification</p>
    <p>
        This is to certify that funds amounting to <strong>&#8369;{{ number_format($caf->amount, 2) }}</strong> are available
        for the purpose of: <em>{{ $caf->purchaseRequest->purpose }}</em>, chargeable against the above fund source,
        leaving a remaining balance of <strong>&#8369;{{ number_format($caf->remaining_budget, 2) }}</strong> at the time of issuance.
    </p>

    <table class="items-table" style="margin-top: 10px;">
        <tr>
            <td style="width: 60%;"><strong>Amount Certified</strong></td>
            <td class="text-right"><strong>&#8369;{{ number_format($caf->amount, 2) }}</strong></td>
        </tr>
        <tr>
            <td><strong>Remaining Budget After This Certificate</strong></td>
            <td class="text-right">&#8369;{{ number_format($caf->remaining_budget, 2) }}</td>
        </tr>
    </table>

    <table class="signatories">
        <tr>
            <td style="width: 33%;">
                <div class="sig-line">{{ $caf->generatedBy?->name ?? '________________________' }}<br>Generated By (Budget Officer)</div>
            </td>
            <td style="width: 33%;">
                <div class="sig-line">{{ $caf->certifiedBy?->name ?? '________________________' }}<br>Certified By</div>
            </td>
            <td style="width: 33%;">
                <div class="sig-line">{{ $caf->approvedBy?->name ?? '________________________' }}<br>Approved By</div>
            </td>
        </tr>
    </table>
</x-pdf-layout>
